apiVersion: storage.k8s.io/v1
# https://kubernetes.io/docs/concepts/storage/storage-classes/
kind: StorageClass
metadata:
  name: managed-nfs-storage
provisioner: kryukov.local/nfs
parameters:
  archiveOnDelete: "false"
