---
apiVersion: v1
kind: Service
metadata:
  name: openresty-srv
  namespace: volumes-sample
  labels:
    app: openresty-srv
spec:
  type: ClusterIP
  selector:
    app: openresty
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-application-access
  namespace: volumes-sample
  labels:
    app: openresty-srv
  annotations:
    kubernetes.io/ingress.class: "nginx-host"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: prometheus.kryukov.local
      http:
        paths:
          - backend:
              serviceName: openresty-srv
              servicePort: 80
            path: /pvc/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openresty
  namespace: volumes-sample
  labels:
    app: openresty
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: openresty
  template:
    metadata:
      labels:
        app: openresty
    spec:
      containers:
        - name: openresty
          image: openresty/openresty:centos-rpm
          imagePullPolicy: IfNotPresent
          env:
            - name: NGINX_HOST
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            limits:
              cpu: "0.2"
              memory: "300Mi"
            requests:
              cpu: "0.1"
              memory: "100Mi"
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - name: pvc-sample
              mountPath: /var/log/nfs
      volumes:
        - name: pvc-sample
          persistentVolumeClaim:
            claimName: openresty-claim
