apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /opt/pv/test-static
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node3.kryukov.local
  persistentVolumeReclaimPolicy: Retain
