apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-static-pv
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: ""
  # volumeMode: Filesystem
  volumeName: test-static

