apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-local-pvc
  namespace: volumes-sample
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: test-local