apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-nfs-pv
  namespace: volumes-sample
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: test-nfs
